c This file has been generated automatically by FeynRules


c Version: 2.3.49   Date: 10. 4. 2025,    1:38
      write(*,*)  ' Couplings of HiggsPortal'
      write(*,*)  ' ---------------------------------'
      write(*,*)  ''
      write(*,*)  ' Real couplings : '
      write(*,1) 'MGVX10=',MGVX10
      write(*,1) 'MGVX14=',MGVX14
      write(*,1) 'MGVX42=',MGVX42
      write(*,1) 'MGVX67=',MGVX67
      write(*,1) 'MGVX68=',MGVX68
      write(*,1) 'MGVX69=',MGVX69
      write(*,1) 'MGVX75=',MGVX75
      write(*,1) 'MGVX76=',MGVX76
      write(*,*)  ''
      write(*,*)  ' Complex couplings : '
      write(*,2) 'MGVX22=',MGVX22
      write(*,2) 'MGVX70=',MGVX70
      write(*,2) 'MGVX73=',MGVX73
      write(*,2) 'MGVX74=',MGVX74
      write(*,2) 'MGVX28=',MGVX28
      write(*,2) 'MGVX29=',MGVX29
      write(*,2) 'MGVX71=',MGVX71
      write(*,2) 'MGVX72=',MGVX72
      write(*,*)  ''
      write(*,*)  ' Left/Right couplings : '
      write(*,4) 'MGVX4(L)=',MGVX4(1),'MGVX4(R)=',MGVX4(2)
      write(*,4) 'MGVX21(L)=',MGVX21(1),'MGVX21(R)=',MGVX21(2)
      write(*,4) 'MGVX23(L)=',MGVX23(1),'MGVX23(R)=',MGVX23(2)
      write(*,4) 'MGVX25(L)=',MGVX25(1),'MGVX25(R)=',MGVX25(2)
      write(*,4) 'MGVX39(L)=',MGVX39(1),'MGVX39(R)=',MGVX39(2)
      write(*,4) 'MGVX58(L)=',MGVX58(1),'MGVX58(R)=',MGVX58(2)
      write(*,4) 'MGVX64(L)=',MGVX64(1),'MGVX64(R)=',MGVX64(2)
      write(*,4) 'MGVX1(L)=',MGVX1(1),'MGVX1(R)=',MGVX1(2)
      write(*,4) 'MGVX2(L)=',MGVX2(1),'MGVX2(R)=',MGVX2(2)
      write(*,4) 'MGVX18(L)=',MGVX18(1),'MGVX18(R)=',MGVX18(2)
      write(*,4) 'MGVX19(L)=',MGVX19(1),'MGVX19(R)=',MGVX19(2)
      write(*,4) 'MGVX20(L)=',MGVX20(1),'MGVX20(R)=',MGVX20(2)
      write(*,4) 'MGVX24(L)=',MGVX24(1),'MGVX24(R)=',MGVX24(2)
      write(*,4) 'MGVX26(L)=',MGVX26(1),'MGVX26(R)=',MGVX26(2)
      write(*,4) 'MGVX27(L)=',MGVX27(1),'MGVX27(R)=',MGVX27(2)
      write(*,4) 'MGVX30(L)=',MGVX30(1),'MGVX30(R)=',MGVX30(2)
      write(*,4) 'MGVX31(L)=',MGVX31(1),'MGVX31(R)=',MGVX31(2)
      write(*,4) 'MGVX32(L)=',MGVX32(1),'MGVX32(R)=',MGVX32(2)
      write(*,4) 'MGVX33(L)=',MGVX33(1),'MGVX33(R)=',MGVX33(2)
      write(*,4) 'MGVX34(L)=',MGVX34(1),'MGVX34(R)=',MGVX34(2)
      write(*,4) 'MGVX35(L)=',MGVX35(1),'MGVX35(R)=',MGVX35(2)
      write(*,4) 'MGVX36(L)=',MGVX36(1),'MGVX36(R)=',MGVX36(2)
      write(*,4) 'MGVX37(L)=',MGVX37(1),'MGVX37(R)=',MGVX37(2)
      write(*,4) 'MGVX38(L)=',MGVX38(1),'MGVX38(R)=',MGVX38(2)
      write(*,4) 'MGVX43(L)=',MGVX43(1),'MGVX43(R)=',MGVX43(2)
      write(*,4) 'MGVX44(L)=',MGVX44(1),'MGVX44(R)=',MGVX44(2)
      write(*,4) 'MGVX45(L)=',MGVX45(1),'MGVX45(R)=',MGVX45(2)
      write(*,4) 'MGVX46(L)=',MGVX46(1),'MGVX46(R)=',MGVX46(2)
      write(*,4) 'MGVX47(L)=',MGVX47(1),'MGVX47(R)=',MGVX47(2)
      write(*,4) 'MGVX48(L)=',MGVX48(1),'MGVX48(R)=',MGVX48(2)
      write(*,4) 'MGVX51(L)=',MGVX51(1),'MGVX51(R)=',MGVX51(2)
      write(*,4) 'MGVX52(L)=',MGVX52(1),'MGVX52(R)=',MGVX52(2)
      write(*,4) 'MGVX53(L)=',MGVX53(1),'MGVX53(R)=',MGVX53(2)
      write(*,4) 'MGVX55(L)=',MGVX55(1),'MGVX55(R)=',MGVX55(2)
      write(*,4) 'MGVX56(L)=',MGVX56(1),'MGVX56(R)=',MGVX56(2)
      write(*,4) 'GG(L)=',GG(1),'GG(R)=',GG(2)
      write(*,*)  ' '
      write(*,*)  ' '
