      call LHA_get_real(npara,param,value,"cabi",cabi,"2.2773600000"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"aEWM1",aEWM1,"1.27900000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Gf",Gf,"1.1663700000000E"
     +//"-05")
      call LHA_get_real(npara,param,value,"aS",aS,"1.1840000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"ymdo",ymdo,"5.0400000000"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"ymup",ymup,"2.5500000000"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"yms",yms,"1.010000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"ymc",ymc,"1.270000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"ymb",ymb,"4.700000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"ymt",ymt,"1.720000000000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"yme",yme,"5.110000000000"
     +//"0E-04")
      call LHA_get_real(npara,param,value,"ymm",ymm,"1.056600000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"ymtau",ymtau,"1.77700000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"msc",msc,"1.000000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"lamS",lamS,"1.0000000000"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"lamHS",lamHS,"1.00000000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"MD",MD,"5.0400000000000E"
     +//"-03")
      call LHA_get_real(npara,param,value,"MU",MU,"2.5500000000000E"
     +//"-03")
      call LHA_get_real(npara,param,value,"MS",MS,"1.0100000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MC",MC,"1.2700000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MB",MB,"4.7000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MT",MT,"1.7200000000000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"Me",Me,"5.1100000000000E"
     +//"-04")
      call LHA_get_real(npara,param,value,"MMU",MMU,"1.056600000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"MTA",MTA,"1.777000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"MZ",MZ,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MW",MW,"7.9824359746197E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MH",MH,"1.2500000000000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"MSc",MSc,"1.000000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"WT",WT,"1.5083364900000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WZ",WZ,"2.4952000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WW",WW,"2.0850000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WH",WH,"4.0700000000000E"
     +//"-03")
      call LHA_get_real(npara,param,value,"WSc",WSc,"1.000000000000"
     +//"0E+00")
