ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MSC__2,MDL_MS,MDL_MU,MDL_MC,MDL_MH,MDL_MW
     $ ,MDL_MT,MDL_MTA,MDL_MD,MDL_ME,MDL_MMU,MDL_MZ,MDL_MB

      COMMON/MASSES/ MDL_MSC__2,MDL_MS,MDL_MU,MDL_MC,MDL_MH,MDL_MW
     $ ,MDL_MT,MDL_MTA,MDL_MD,MDL_ME,MDL_MMU,MDL_MZ,MDL_MB


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WT,MDL_WW

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WT,MDL_WW


      DOUBLE COMPLEX GC_92, GC_109, GC_112, GC_125, GC_136

      COMMON/COUPLINGS/ GC_92, GC_109, GC_112, GC_125, GC_136

