c This file has been generated automatically by FeynRules
c Version: 2.3.49   Date: 10. 4. 2025,    1:38

      double precision G
      common/strong/ G

      double complex gal(2)
      common/weak/ gal

      double precision DUM0
      common/FRDUM0/ DUM0

      double precision DUM1
      common/FRDUM1/ DUM1


c Masses : 
      double precision MD,MU,MS,MC,MB,MT,Me,MMU,MTA,MZ,MW,MH,MSc
      common/masses/ MD,MU,MS,MC,MB,MT,Me,MMU,MTA,MZ,MW,MH,MSc

c Widths : 
      double precision WT,WZ,WW,WH,WSc
      common/widths/ WT,WZ,WW,WH,WSc

c Interactions associated with HiggsPortal:
      double precision MGVX10,MGVX14,MGVX42,MGVX67,MGVX68,MGVX69,MG
     +VX75,MGVX76
      common/real_coupl_HiggsPortal/ MGVX10,MGVX14,MGVX42,MGVX67,MG
     +VX68,MGVX69,MGVX75,MGVX76

      double complex MGVX22,MGVX70,MGVX73,MGVX74,MGVX28,MGVX29,MGVX
     +71,MGVX72
      common/comp_coupl_HiggsPortal/ MGVX22,MGVX70,MGVX73,MGVX74,MG
     +VX28,MGVX29,MGVX71,MGVX72

      double complex MGVX4(2),MGVX21(2),MGVX23(2),MGVX25(2),MGVX39(
     +2),MGVX58(2),MGVX64(2),MGVX1(2),MGVX2(2),MGVX18(2),MGVX19(2)
     +,MGVX20(2),MGVX24(2),MGVX26(2),MGVX27(2),MGVX30(2),MGVX31(2)
     +,MGVX32(2),MGVX33(2),MGVX34(2),MGVX35(2),MGVX36(2),MGVX37(2)
     +,MGVX38(2),MGVX43(2),MGVX44(2),MGVX45(2),MGVX46(2),MGVX47(2)
     +,MGVX48(2),MGVX51(2),MGVX52(2),MGVX53(2),MGVX55(2),MGVX56(2)
     +,GG(2)
      common/chiral_coupl_HiggsPortal/ MGVX4,MGVX21,MGVX23,MGVX25,M
     +GVX39,MGVX58,MGVX64,MGVX1,MGVX2,MGVX18,MGVX19,MGVX20,MGVX24,
     +MGVX26,MGVX27,MGVX30,MGVX31,MGVX32,MGVX33,MGVX34,MGVX35,MGVX
     +36,MGVX37,MGVX38,MGVX43,MGVX44,MGVX45,MGVX46,MGVX47,MGVX48,M
     +GVX51,MGVX52,MGVX53,MGVX55,MGVX56,GG

