c This file has been generated automatically by FeynRules
c Version: 2.3.49   Date: 10. 4. 2025,    1:38

c External Parameters :
      double precision cabi,aEWM1,Gf,aS,ymdo,ymup,yms,ymc,ymb,ymt,y
     +me,ymm,ymtau,msc,lamS,lamHS
      common/external_params/ cabi,aEWM1,Gf,aS,ymdo,ymup,yms,ymc,ym
     +b,ymt,yme,ymm,ymtau,msc,lamS,lamHS

c Internal Parameters :
      double precision FRPi,aEW,sw2,ee,cw,sw,gw,g1,vev,lam,muH,ye,y
     +m,ytau,yup,yc,yt,ydo,ys,yb,Sqrt2,SqrtPi,Psw2,Pcw2,ggT1
      common/internal_params_R/ FRPi,aEW,sw2,ee,cw,sw,gw,g1,vev,lam
     +,muH,ye,ym,ytau,yup,yc,yt,ydo,ys,yb,Sqrt2,SqrtPi,Psw2,Pcw2,g
     +gT1
      double complex CKM1x1,CKM1x2,CKM1x3,CKM2x1,CKM2x2,CKM2x3,CKM3
     +x1,CKM3x2,CKM3x3,CONJCKM2x3,CONJCKM3x3,CONJCKM1x3,CONJCKM2x1
     +,CONJCKM3x1,CONJCKM1x1,CONJCKM2x2,CONJCKM3x2,CONJCKM1x2
      common/internal_params_C/ CKM1x1,CKM1x2,CKM1x3,CKM2x1,CKM2x2,
     +CKM2x3,CKM3x1,CKM3x2,CKM3x3,CONJCKM2x3,CONJCKM3x3,CONJCKM1x3
     +,CONJCKM2x1,CONJCKM3x1,CONJCKM1x1,CONJCKM2x2,CONJCKM3x2,CONJ
     +CKM1x2
