ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MTA,MDL_MW,MDL_MSC__2,MDL_MC,MDL_MD
     $ ,MDL_MH,MDL_MT,MDL_MZ,MDL_MB,MDL_ME,MDL_MU,MDL_MMU

      COMMON/MASSES/ MDL_MS,MDL_MTA,MDL_MW,MDL_MSC__2,MDL_MC,MDL_MD
     $ ,MDL_MH,MDL_MT,MDL_MZ,MDL_MB,MDL_ME,MDL_MU,MDL_MMU


      DOUBLE PRECISION MDL_WZ,MDL_WW,MDL_WH,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WW,MDL_WH,MDL_WT


      DOUBLE COMPLEX GC_11, GC_77, GC_78, GC_79, GC_81, GC_82, GC_83,
     $  GC_92, GC_104, GC_109, GC_112, GC_125, GC_136

      COMMON/COUPLINGS/ GC_11, GC_77, GC_78, GC_79, GC_81, GC_82,
     $  GC_83, GC_92, GC_104, GC_109, GC_112, GC_125, GC_136

