ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of DarkMatter_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_109 = ', GC_109
      WRITE(*,2) 'GC_112 = ', GC_112
      WRITE(*,2) 'GC_125 = ', GC_125
      WRITE(*,2) 'GC_136 = ', GC_136
