ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of DarkMatter_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_82 = ', GC_82
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_104 = ', GC_104
      WRITE(*,2) 'GC_109 = ', GC_109
      WRITE(*,2) 'GC_112 = ', GC_112
      WRITE(*,2) 'GC_125 = ', GC_125
      WRITE(*,2) 'GC_136 = ', GC_136
