ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MMU,MDL_MH,MDL_MC,MDL_MW,MDL_MTA,MDL_MU
     $ ,MDL_MT,MDL_MB,MDL_MSC__2,MDL_MD,MDL_MZ,MDL_MS,MDL_ME

      COMMON/MASSES/ MDL_MMU,MDL_MH,MDL_MC,MDL_MW,MDL_MTA,MDL_MU
     $ ,MDL_MT,MDL_MB,MDL_MSC__2,MDL_MD,MDL_MZ,MDL_MS,MDL_ME


      DOUBLE PRECISION MDL_WT,MDL_WZ,MDL_WW,MDL_WH

      COMMON/WIDTHS/ MDL_WT,MDL_WZ,MDL_WW,MDL_WH


      DOUBLE COMPLEX GC_92, GC_109, GC_112, GC_125, GC_136

      COMMON/COUPLINGS/ GC_92, GC_109, GC_112, GC_125, GC_136

