ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MT,MDL_MU,MDL_MMU,MDL_MTA,MDL_MD,MDL_MS
     $ ,MDL_MC,MDL_MH,MDL_MSC__2,MDL_MZ,MDL_MW,MDL_ME,MDL_MB

      COMMON/MASSES/ MDL_MT,MDL_MU,MDL_MMU,MDL_MTA,MDL_MD,MDL_MS
     $ ,MDL_MC,MDL_MH,MDL_MSC__2,MDL_MZ,MDL_MW,MDL_ME,MDL_MB


      DOUBLE PRECISION MDL_WH,MDL_WZ,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WH,MDL_WZ,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_92, GC_109, GC_112, GC_125, GC_136

      COMMON/COUPLINGS/ GC_92, GC_109, GC_112, GC_125, GC_136

